name: Deploy docs

on:
  push:
    branches: ['master']

env:
  DEBIAN: noninteractive

jobs:
  deploy-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: leafo/gh-actions-lua@v8.0.0
      - uses: leafo/gh-actions-luarocks@v4.0.0
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: |
          luarocks install ldoc
          luarocks install lua-discount
          luarocks install xml2lua

      - name: Generate documentation
        run: |
          mkdir -p 'out'
          make protocol -C examples
          ldoc wau --config 'docs/config.ld' --dir 'out/docs'
          touch out/docs/.nojekyll

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: out/docs

