name: Main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.3"
      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Update system
        run: sudo apt update -y

      - name: Install dependencies through apt
        run: |
          sudo apt install -y --no-install-recommends \
            sway \
            liblua5.3-dev libwayland-dev \
            meson ninja-build cmake
          lua -v

      - name: Install cffi-lua
        run: |
          git clone https://github.com/q66/cffi-lua cffi
          git checkout d92fcc95bbde23a44e61b0c86737106246db5904
          cd cffi
          mkdir build
          cd build
          meson -Dlua_version=5.3 ..
          ninja all
          cp cffi.so ../..

      - name: Run Tests
        env:
          WLR_BACKENDS: headless
          WLR_RENDERER: pixman
          WLR_LIBINPUT_NO_DEVICES: 1
          GTK_USE_PORTAL: 0
        run: |
          export XDG_RUNTIME_DIR=/tmp/runtime
          mkdir -p $XDG_RUNTIME_DIR
          chmod 0700 $XDG_RUNTIME_DIR
          sway -d &
          sleep 20
          cd tests
          ./run.sh
          swaymsg exit || true
