name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends "lua5.3" luarocks sway meson ninja-build
          luarocks install cffi-lua --lua-version=5.3

      - name: Run Tests
        run: |
          WLR_RENDERER=pixman WLR_BACKENDS=headless sway &
          cd tests
          ./run.sh
