name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.3"
      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends sway meson ninja-build
          luarocks install cffi-lua

      - name: Run Tests
        run: |
          WLR_RENDERER=pixman WLR_BACKENDS=headless sway &
          cd tests
          ./run.sh
